quadrantChart
  title 1. Programming Languages
  x-axis Backend --> Frontend
  y-axis Rudimentary knowledge --> High knowledge & experience
  SQL: [0.08, 0.8]
  PHP: [0.15, 0.81]
  JavaScript: [0.6, 0.8]
  TypeScript: [0.6, 0.7]
  HTML & CSS*: [0.9, 0.85]
  C#: [0.2, 0.45]
  Python: [0.4, 0.5]
  C: [0.1, 0.1]
  Rust: [0.2, 0.17]
  Bash: [0.3, 0.1]