quadrantChart
  title 3. Tools & Services
  x-axis Local --> Cloud
  y-axis Rudimentary knowledge --> High knowledge & experience
  VS Code + GH Codespaces: [0.3, 0.9]
  Docker + Docker Compose: [0.35, 0.7]
  ESLint: [0.1, 0.7]
  PHPStorm: [0.2, 0.85]
  Cloudflare Workers: [0.8, 0.6]
  Vercel: [0.85, 0.9]
  Laravel Envoyer: [0.8, 0.85]
  Laravel Forge: [0.8, 0.8]
  GH Actions: [0.8, 0.47]
  AWS Lambda: [0.8, 0.15]